name: Auto Generate Blog Post

on:
  schedule:
    # Runs at 00:00 and 12:00 UTC every day (twice daily)
    - cron: '0 0,12 * * *'
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug logging'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    # Prevent multiple instances from running simultaneously
    concurrency:
      group: generate-post
      cancel-in-progress: false
    
    # Environment variables available to all steps
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check content calendar status
        id: check-calendar
        run: |
          echo "Checking for posts to generate..."
          NEXT_POST=$(node -e "
            const fs = require('fs');
            const calendar = JSON.parse(fs.readFileSync('./content-calendar.json', 'utf-8'));
            const nextPost = calendar.posts.find(p => !p.status || p.status !== 'Done');
            if (nextPost) {
              console.log('FOUND');
              console.log('POST_ID=' + nextPost.id);
            } else {
              console.log('NONE');
            }
          ")
          
          if [[ "$NEXT_POST" == *"FOUND"* ]]; then
            echo "has_post=true" >> $GITHUB_OUTPUT
            POST_ID=$(echo "$NEXT_POST" | grep "POST_ID=" | cut -d'=' -f2)
            echo "post_id=$POST_ID" >> $GITHUB_OUTPUT
            echo "📝 Found post to generate: $POST_ID"
          else
            echo "has_post=false" >> $GITHUB_OUTPUT
            echo "✅ All posts are already generated"
          fi
          
      - name: Generate blog post content
        if: steps.check-calendar.outputs.has_post == 'true'
        run: |
          echo "🚀 Generating post: ${{ steps.check-calendar.outputs.post_id }}"
          node scripts/createNextPost.js
          
      - name: Generate slides
        if: steps.check-calendar.outputs.has_post == 'true'
        run: |
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          echo "🎯 Generating slides for: $POST_ID"
          
          # Generate comprehensive downloadable slides with 12+ detailed takeaways
          node scripts/generateComprehensiveSlides.js generate-post "$POST_ID" || {
            echo "⚠️ Comprehensive slide generation failed, continuing"
          }
          
      - name: Final post processing
        if: steps.check-calendar.outputs.has_post == 'true'
        run: |
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          echo "🔄 Running final post-processing for: $POST_ID"
          
          # Re-run post-processing to add slide links now that slides exist
          node scripts/postProcessBlog.js "$POST_ID" || {
            echo "⚠️ Final post-processing failed, continuing"
          }
          
      - name: Generate podcast content
        if: steps.check-calendar.outputs.has_post == 'true'
        run: |
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          echo "🎙️ Generating podcast for: $POST_ID"
          
          # Generate podcast (transcript and audio if TTS works)
          npm run generate-podcast generate "$POST_ID" || {
            echo "⚠️ Podcast generation failed, continuing without audio"
          }
          
      - name: Update header image
        if: steps.check-calendar.outputs.has_post == 'true'
        run: |
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          echo "🖼️ Updating header image for: $POST_ID"
          
          # Update header image with post type and reading time
          npm run update-header-images "$POST_ID" || {
            echo "⚠️ Header image update failed, continuing"
          }
          
      - name: Add podcast player
        if: steps.check-calendar.outputs.has_post == 'true'
        run: |
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          echo "🎧 Adding podcast player for: $POST_ID"
          
          # Add podcast player to the post if transcript exists
          npm run add-podcast-players "$POST_ID" || {
            echo "⚠️ Podcast player addition failed, continuing"
          }
          
      - name: Verify generation success
        if: steps.check-calendar.outputs.has_post == 'true'
        id: verify
        run: |
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          
          # Check if files were created
          if [ -f "content/${POST_ID}.md" ]; then
            echo "✅ Markdown file created: content/${POST_ID}.md"
            echo "markdown_created=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Markdown file not found"
            echo "markdown_created=false" >> $GITHUB_OUTPUT
          fi
          
          if [ -f "public/${POST_ID}.jpeg" ]; then
            echo "✅ Image file created: public/${POST_ID}.jpeg"
            echo "image_created=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Image file not found (may have failed)"
            echo "image_created=false" >> $GITHUB_OUTPUT
          fi
          
          # Check for podcast files
          if [ -f "public/podcasts/transcripts/${POST_ID}-transcript.txt" ]; then
            echo "✅ Podcast transcript created: public/podcasts/transcripts/${POST_ID}-transcript.txt"
            echo "transcript_created=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Podcast transcript not found"
            echo "transcript_created=false" >> $GITHUB_OUTPUT
          fi
          
          if [ -f "public/podcasts/audio/${POST_ID}.wav" ]; then
            echo "✅ Podcast audio created: public/podcasts/audio/${POST_ID}.wav"
            echo "audio_created=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Podcast audio not found (TTS may have failed)"
            echo "audio_created=false" >> $GITHUB_OUTPUT
          fi
          
          # Check for slides
          if [ -f "public/resources/slides/${POST_ID}/slides.html" ]; then
            echo "✅ Slides created: public/resources/slides/${POST_ID}/"
            echo "slides_created=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Slides not found"
            echo "slides_created=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check-calendar.outputs.has_post == 'true' && steps.verify.outputs.markdown_created == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add all changes
          git add -A
          
          # Create commit message
          POST_ID="${{ steps.check-calendar.outputs.post_id }}"
          COMMIT_MSG="🤖 Auto-generated blog post: ${POST_ID}

          - Generated content for ${POST_ID}
          - Created markdown file and header image
          - Generated podcast transcript and audio
          - Updated header image with post type and reading time
          - Added podcast player to post content
          - Generated downloadable slides with key takeaways
          - Applied content sanitization
          - Added internal links and resources
          - Updated content calendar status

          Generated by GitHub Actions workflow"
          
          # Commit changes
          git commit -m "$COMMIT_MSG" || {
            echo "No changes to commit"
            exit 0
          }
          
          # Push to main branch
          git push origin main
          
      - name: Build and test site
        if: steps.check-calendar.outputs.has_post == 'true' && steps.verify.outputs.markdown_created == 'true'
        run: |
          echo "🔨 Building site to verify changes..."
          npm run build
          
      - name: Send success notification
        if: steps.check-calendar.outputs.has_post == 'true' && steps.verify.outputs.markdown_created == 'true'
        run: |
          echo "✅ Successfully generated post: ${{ steps.check-calendar.outputs.post_id }}"
          echo "📊 Summary:"
          echo "  - Markdown: ${{ steps.verify.outputs.markdown_created }}"
          echo "  - Header Image: ${{ steps.verify.outputs.image_created }}"
          echo "  - Podcast Transcript: ${{ steps.verify.outputs.transcript_created }}"
          echo "  - Podcast Audio: ${{ steps.verify.outputs.audio_created }}"
          echo "  - Downloadable Slides: ${{ steps.verify.outputs.slides_created }}"
          echo "  - Build: Success"
          echo ""
          echo "🎧 Podcast features:"
          echo "  - Data and SaaS conversation format"
          echo "  - Direct, no-nonsense communication style"
          echo "  - Estimated 4-7 minute listening time"
          echo "  - Professional accents (if audio generated)"
          
      - name: Handle generation failure
        if: failure() && steps.check-calendar.outputs.has_post == 'true'
        run: |
          echo "❌ Failed to generate post: ${{ steps.check-calendar.outputs.post_id }}"
          echo "Check the logs above for error details"
          
      - name: Log failure details
        if: failure() && steps.check-calendar.outputs.has_post == 'true'
        run: |
          echo "::error::Failed to generate post: ${{ steps.check-calendar.outputs.post_id }}"
          echo "❌ Generation failed for post: ${{ steps.check-calendar.outputs.post_id }}"
          echo "📋 Details:"
          echo "  - Markdown created: ${{ steps.verify.outputs.markdown_created || 'unknown' }}"
          echo "  - Image created: ${{ steps.verify.outputs.image_created || 'unknown' }}"
          echo "  - Transcript created: ${{ steps.verify.outputs.transcript_created || 'unknown' }}"
          echo "  - Audio created: ${{ steps.verify.outputs.audio_created || 'unknown' }}"
          echo "  - Slides created: ${{ steps.verify.outputs.slides_created || 'unknown' }}"
          echo ""
          echo "To manually generate, run:"
          echo "  npm run create-post"
          echo "  npm run generate-podcast generate [post-id]"
          echo "  npm run update-header-images [post-id]"
          echo "  npm run add-podcast-players [post-id]"